server:
  port: 7003
server.error.include-message: always

# Change to "none" in a production environment
spring.jpa.hibernate.ddl-auto: update

# Spring datasource connection
spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.jfcdevs.app: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource:
  url: jdbc:mysql://mysql/review-db